//
// Created by Petr on 11.02.2021.
//

#ifndef VITEJTE_POSTGRESQL_SERVICE__LIST_DEVICES_H
#define VITEJTE_POSTGRESQL_SERVICE__LIST_DEVICES_H


void listDevices();


#endif//VITEJTE_POSTGRESQL_SERVICE__LIST_DEVICES_H
